<% PASSWORD_FILE = File.join(RAILS_ROOT, '..', '..', 'shared', 'config', 'dbpassword') %>

development:
  adapter: mysql
  database: <%= PROJECT_NAME %>_development
  username: root
  password: 
  host: localhost
  encoding: utf8
  collation: utf8_general_ci
  
test:
  adapter: mysql
  database: <%= PROJECT_NAME %>_test
  username: root
  password: 
  host: localhost
  encoding: utf8
  collation: utf8_general_ci
  

production:
  adapter: mysql
  database: <%= PROJECT_NAME %>_production
  username: root
  password: 
  host: localhost
  encoding: utf8
  collation: utf8_general_ci
