app_name: jsroll
app_title: JSRoll
default_title: "JSRoll : Community Filtered JavaScript News"
sub_title: "Community-maintained JavaScript News"
app_url: http://www.jsroll.com/
rss_url: http://feeds.feedburner.com/jsroll
meta_keywords: "javascript, javascript news, javascript blog, js, JavaScript, JS Frameworks, JavaScript Frameworks, Libraries, jQuery, Dojo, Prototype, Scriptaculous, Moo"
meta_author: "Chris Williams"
body_class: jsroll

# Set this to true for a more fancy interface, but for the cost of page load time
uses_javascript: false

# Edit expiration default: 60 (this means that editing ends 60 minutes after last update of item)
# Set to 0 or omit to always allow editing of items by its owner
edit_expiration_in_minutes: 60

# ga: UA-2237791-7
sidebar: |-
  <h3>What?</h3><p>JSRoll is a community driven JavaScript links site, based off the codebase provided by <a href="http://www.rubyflow.com">RubyFlow</a>. Items are not added automatically, but chosen and summarized by the community, resulting in a high quality of links.</p>
  <h3>How?</h3><p>Enjoy the links, comment or <a href="/items/new">make a post</a> of your own. You don't need to be signed in!</p>
  <p><em>Note: If you're not signed in, your byline is unlinked and your links are made "nofollow" to prevent spam. You also get CAPTCHAed!</em></p>
  <h3>Who?</h3><p>JSRoll is maintained by <a href="http://www.voodootikigod.com">Chris Williams</a> of <a href="http://www.iterativedesigns.com">Iterative Designs</a> as a way to further build the JavaScript community. We are the crazy people behind <a href="http://www.jsconf2009.com">JSConf 2009</a> as well. The original RubyFlow was built by <a href="http://peterc.org/">Peter Cooper</a> of <a href="http://www.rubyinside.com/" rel="nofollow">Ruby Inside</a>, but is ultimately a community site.</p>
  <p><small>Yes, this site is influenced by <a href="http://www.metafilter.com/">MetaFilter</a>. I wrote a popular MetaFilter <a href="http://www.google.com/search?q=metafilter+freefilter">clone</a> back in the day so it's okay!</small></p>
  <p><a href="http://feeds.feedburner.com/jsroll"><img src="http://feeds.feedburner.com/~fc/jsroll?bg=cc0000&amp;fg=FFFFFF&amp;anim=0" height="26" width="88" style="border:0" alt="" /></a></p>